### ISSUE TITLE
Fatal error: Windows.h: No such file or directory

### ISSUE THREAD

**Issue by lachanviet** [zimnyaa/xyrella#2]
I try this command "python build.py -s xll.bin" and got this below error
/home/kali/.cache/nim/temp_xll_6_d/@mtemp_xll_6.nim.c:368:10: fatal error: Windows.h: No such file or directory
I try to change the Windows.h to windows.h manually in mtemp_xll_6.nim.c but it still not work.
Could you suggest any solution ? May thanks!

**Comment by zimnyaa** [comment]
The `.c` file gets regenerated every time you try to rebuild the XLL, so changing it will not work. The issue is with the filename -- Linux is case-sensitive, Windows is not, and in Linux there is no `Windows.h`, only `windows.h`.  I fixed it on my machine a while ago with some hack, but I've fixed it now in `syscalls.nim`, try pulling the newer version of the repo.
